server:
  port: 8326
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://127.00.1:3306/blog-demo?useSSL=false&serverTimezone=UTC
    username: root
    password: chen0809
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

blog:
  security:
    enabled: true # 权限认证开关，默认为true
    token-timeout: 3 # token超时时间，默认3小时，单位：小时
    token-refresh-per: 30 # token过期前多久刷新，默认20分钟，单位：分钟
